Failure # 1 (occurred at 2021-10-31_21-05-37)
Traceback (most recent call last):
  File "/home/setsumi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 812, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/setsumi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 767, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/setsumi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/home/setsumi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/ray/worker.py", line 1621, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TuneError): [36mray::ImplicitFunc.train_buffered()[39m (pid=18467, ip=192.168.0.11, repr=<types.ImplicitFunc object at 0x7f4d78088590>)
  File "/home/setsumi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/ray/tune/trainable.py", line 189, in train_buffered
    result = self.train()
  File "/home/setsumi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/ray/tune/trainable.py", line 248, in train
    result = self.step()
  File "/home/setsumi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/ray/tune/function_runner.py", line 379, in step
    self._report_thread_runner_error(block=True)
  File "/home/setsumi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/ray/tune/function_runner.py", line 527, in _report_thread_runner_error
    ("Trial raised an exception. Traceback:\n{}".format(err_tb_str)
ray.tune.error.TuneError: Trial raised an exception. Traceback:
[36mray::ImplicitFunc.train_buffered()[39m (pid=18467, ip=192.168.0.11, repr=<types.ImplicitFunc object at 0x7f4d78088590>)
  File "/home/setsumi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/ray/tune/function_runner.py", line 260, in run
    self._entrypoint()
  File "/home/setsumi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/ray/tune/function_runner.py", line 329, in entrypoint
    self._status_reporter.get_checkpoint())
  File "/home/setsumi/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/ray/tune/function_runner.py", line 594, in _trainable_func
    output = fn()
  File "train.py", line 145, in training_f
    optimizer = optim.NAdam( model.parameters(), lr=config['lr'] )
AttributeError: module 'torch.optim' has no attribute 'NAdam'

